### ISSUE TITLE
Slash chords?

### ISSUE THREAD

**Issue by T-vK** [tombatossals/chords-db#1]
Where would you put a slash chord like `C/G`? Would you just add another suffix for `C`?

**Comment by tombatossals** [comment]
Well, I would consider a slash chord as a suffix, a "C" chord with a "/G" suffix.

But maybe it would be more semantic to add a new property to the JSON. Something like, for example "Dadd9/F#"
```
{
  key: 'D',
  suffix: 'add9'
  slash: 'F#',
  position: [ ... ]
}
```

I'm open to suggestions. What do you think?

**Comment by T-vK** [comment]
I think you are right, a new property would make more sense. 
I might add that some time in the future. Is there a good source to gather data like commonly accepted finger placement?

**Comment by tombatossals** [comment]
You're welcome to contribute if you find some time.

I looked for a trusted source of chords and chord finger placement and didn't find anything. :( I'm using every source I can, books, android apps, and my own experience for this. :)
