### ISSUE TITLE
On guitar all of the B chords are actually A chords

### ISSUE THREAD

**Issue by rsml** [tombatossals/chords-db#3]
The guitar chords for the key of B are incorrect. The current ones are showing the corresponding A chords. I checked for all of the suffixes and for various positions.

For example this B major is actually an A major: https://github.com/tombatossals/chords-db/blob/master/src/db/guitar/chords/B/major.js.

**Comment by tombatossals** [comment]
You're right. I have to redo these JSON files.

Thanks for reporting

**Comment by tombatossals** [comment]
Solved
