### ISSUE TITLE
Cm11 and CM11 are the same on guitar

### ISSUE THREAD

**Issue by rsml** [tombatossals/chords-db#4]
Both Cm11 and CM11 as showing up as the same notes on guitar. I'm not sure which is incorrect:

https://github.com/tombatossals/chords-db/blob/master/src/db/guitar/chords/C/maj11.js
https://github.com/tombatossals/chords-db/blob/master/src/db/guitar/chords/C/m11.js

**Comment by tombatossals** [comment]
Totally right! I have fixed it in the last commit.

Thanks for reporting
