### ISSUE TITLE
ukelele or ukulele?

### ISSUE THREAD

**Issue by sonph** [tombatossals/chords-db#5]
Hey thanks a lot for this library.

I noticed you spell `ukulele` as `ukelele` in e.g. `lib/ukelele.json` and in `lib/instruments.json` (haven't taken a look in `src/`). Regardless of whether `ukelele` is a correct spelling, I think it's a very good idea to `s/ukelele/ukulele/g` as it is still the most widely used spelling.

**Comment by tombatossals** [comment]
Upssss you're totally right, is mispelled in english, didn't notice it in my native language it's called ukelele :P

I have solved it and published a new version. Thanks for reporting!

**Comment by sonph** [comment]
Thanks 🍻:)
