### ISSUE TITLE
Em/D# and similar chords

### ISSUE THREAD

**Issue by szaza** [tombatossals/chords-db#6]
Hi, I created a little tool based on your chord collection database, so very big thanks for your work!
Today I wanted to create a tab that contains many chords like Em/D#, Em/D, Em/C#, however I cannot find these chords in the database. Is there a possibility to add these chords to the collection?

**Comment by tombatossals** [comment]
Hey there. Yes of course, they can be added if they currently not exists in the database.

Do you have the figures of these chords and variations? You can make a Pull Request with this information and I will merge it in the repository, or I can add it if you provide me a link with the chord figures.

**Comment by szaza** [comment]
Hi, I'm planning to extend your db in the next weeks, I'm not sure when I'll have enough time to do it, but I'll try to do it as soon as possible. I would only request you to add me as **contributor** to the project, in order to have the possibility to create new development branch and pull request.

However if you start working on it before me, you can find the slash chords on the following sites:
https://www.guitar-chord.org/slash-chords.html
http://www.all-guitar-chords.com/index.php?ch=C%2FE&get=Get (in the last columns)

I'm also thinking on: how to name the suffixes in case of slash chords like: C/G?
As I know files cannot start with "/" character. Maybe, we could name the suffix as "sG".
What do you think about this idea?

**Comment by tombatossals** [comment]
I'm glad that someone find interesting the database, I used a couple of guitar cord books to add the initial chords to the database, but there's a lot missing for sure. I'm adding you as a contributor.

The suffix "sG" seems perfect to me.

**Comment by szaza** [comment]
Hi, I added the most frequent used slash chords on the branch [zsz-adding-slash-chords](https://github.com/tombatossals/chords-db/tree/zsz-adding-slash-chords). I also created a test page for chords on my site, so you can easily check them here: https://guitar-chords.org/chord-collection. Of course there are a lot of missing chords that should be added.

Unfortunately, I cannot execute the generate.js, so I cannot test whether the new chords crash anything in your program. I'm using Node v12.13.0 and I tried to run as _node generate.js_. Could you extend the README.MD to include the generation commands?

**Comment by tombatossals** [comment]
I'm going to extend the README to include some basics.

**Comment by tombatossals** [comment]
I added some basic information about how to  generate the chord libary in the README.

Let me know if you think some more detailed info should be added.
